# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: "Harley Farms Goat Dairy, Award Winning Goat Cheese, Farm Dinners & Goat Tours, Pescadero, CA"

url: "http://harleyfarms.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# include: ['_pages']
gems:    ['jekyll-paginate']

paginate: 6
paginate_path: "/news/page:num/"

array: []
